### ISSUE TITLE
Improve error handling before launching downstream pipelines

### ISSUE THREAD

**Issue by erikwaskiewicz** [AWGL/IlluminaQC#1]
This happened:

- IlluminaQC hit an error midway through running
- It made the results folder for 1 sample and kicked off GermlineEnrichment script 1 for that sample only, then aborted
- GE script 1 finished for that sample and automatically queued script 2:
  - The check for launching script 2 compares the number of gVCFs made against the number of folders in the results folder (should be one per sample)
  - Because only one folder was made during IlluminaQC, these were equal and script 2 could be queued
- The cluster was busy so script 2 joined a queue and didn't kick off straight away
- In the meantime, IlluminaQC was re queued and GE script 1 restarted for the whole run, we didn't notice the other script 2 in the job queue
- This eventually led to there being two script 2's running on the same data at the same time

TL,DR: The error handling at the end of IlluminaQC needs to be better when kicking off the pipeline

**Comment by smrey** [comment]
Error handling added on branch issue1:

- list of samples created from sample sheet and deleted at the end of the pipeline

  - this is compared to 
   -output from variables file generator
   -fastqs generated
   -number of directories created in data results < initiation of pipeline is now conditional on this test passing

Tested working on development cluster for 3 runs
